# print("salom")
# print(1)
# print(12)
# print(123)
# print(1234)
# print(12345)
# print("    1")
# print("   12")
# print("  123")
# print(" 1234")
# print("12345")
# print(1)
# print(12)
# print(123)
# print(1234)
# print(12345)
# print(1234)
# print(123)
# print(12)
# print(1)

# print("     /\\            ")
# print("    /  \\           ")
# print("   /    \\          ")
# print("  /      \\         ")
# print(" /        \\        ")
# print("/|________|\\       ")
# print(" |        |         ")
# print(" |   ____ |         ")
# print(" |   |__| |         ")            
# print(" |        |         ")    
# print(" |________|         ")
# print("------------------------------------------------------")
# print("|    conuntry    |   name  |   profsion    |    age  |") 
# print("------------------------------------------------------")
# print("|    Germany     |   Tomas |   Actor       |    35   |") 
# print("------------------------------------------------------")
# print("|    England     |   Jery  |   Singer      |    27   |") 
# print("------------------------------------------------------")
# print("|    Spain       |   Xose  |   Footballer  |    30   |")
# print("------------------------------------------------------") 
# print("|    France      |   Jhon  |   Engineer    |    39   |")
# print("------------------------------------------------------") 


print ("         * * * * * * * * * * * ")
print ("       * *                 * * ")
print ("      *  *                *  * ")
print ("     *   *               *   * ")
print ("    *    *              *    * ")
print ("   * * * * * * * * * * *     * ")
print ("   *     *             *     * ")
print ("   *     *             *     * ") 
print ("   *     *             *     * ")
print ("   *     *             *     * ")
print ("   *     * * * * * * * * * * * ")
print ("   *    *              *    *  ")
print ("   *   *               *   *   ")
print ("   *  *                *  *    ")
print ("   * *                 * *     ")
print ("   * * * * * * * * * * *       ")

# print ("  *******")
# print ("*   *    *")
# print ("*        ****")
# print (" *****    * ")
# print ("     *    ****")
# print ("     *    *    * *    ***")
# print ("     *    *   *   *  *   *    ***            * *        ")
# print ("     *    *   *   *  *   *   *   *         *   *    ") 
# print ("     *    *   *   *  *   *   *   *       *    *    ")
# print ("     *     ****   ****   *********     *     *     ")
# print ("     *                              *       *    ")
# print ("     *                                    *      ")
# print ("     *                                  *      ")
# print ("     *                                *     ")
# print ("       *        ***********         *         ")
# print ("       *      *            *      *       ")
# print ("       *      *            *     *   ")
# print ("       *      *            *     *    ")
# print ("     *        *          *       *     ")
# print ("     *********           ********        ")



# print("*****      *     ****     ****      ****     *****   *   * ")
# print("*         * *    *   *   *    *     *   *      *      * *  ")
# print("*****    *****   ****    *    *     ****       *       *   " )
# print("*        *   *   *   *   *    *     *   *      *       *   ")
# print("*        *   *   *    *   ****      ****     *****     *   ")